apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cms-secrets
  namespace: production
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cms-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: hayyacom/production/cms/secrets
