apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayyacom-cms
spec:
  replicas: 2
  template:
    metadata:
      labels:
        environment: production
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - hayyacom-cms
                topologyKey: kubernetes.io/hostname
