apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - pairs:
      app.kubernetes.io/name: hayyacom-cms
      app.kubernetes.io/component: cms
      app.kubernetes.io/part-of: hayyacom-platform

resources:
  - deployment.yaml
  - service.yaml
