apiVersion: v1
kind: Service
metadata:
  name: hayyacom-cms
  labels:
    app: hayyacom-cms
    component: cms
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hayyacom-cms
